"""시크릿/환경변수 관리 모듈"""

from __future__ import annotations

import os

from dotenv import dotenv_values

from .config import get_project_root


class SecretsManager:
    """환경변수/시크릿 관리 (.env 파일에서 읽기 전용)"""

    def __init__(self, env_file: str = ".env"):
        self.env_file = get_project_root() / env_file
        self._cache: dict[str, str] = {}
        self._load()

    def _load(self) -> None:
        """환경변수 파일 로드

        .env 파일에서 환경변수를 읽어 내부 캐시에 저장합니다.
        파일이 없으면 빈 캐시로 유지됩니다.
        """
        if self.env_file.exists():
            values = dotenv_values(self.env_file)
            self._cache = {k: v for k, v in values.items() if v is not None}

    def get(self, key: str, default: str = "") -> str:
        """환경변수 값 조회

        Args:
            key: 환경변수 이름
            default: 값이 없을 때 기본값

        Returns:
            환경변수 값 (캐시 → os.environ → 기본값 순서로 조회)
        """
        return self._cache.get(key, os.environ.get(key, default))

    def list(self) -> dict[str, str]:
        """모든 환경변수 목록 반환

        Returns:
            환경변수 딕셔너리 (복사본)
        """
        return self._cache.copy()

    def list_masked(self) -> dict[str, str]:
        """마스킹된 환경변수 목록 반환 (보안)

        민감한 값을 부분적으로 마스킹하여 안전하게 표시합니다.
        - 8자 초과: 앞 4자 + 마스킹 + 뒤 4자
        - 8자 이하: 전체 마스킹
        - 빈 값: "(empty)" 표시

        Returns:
            마스킹된 환경변수 딕셔너리

        Example:
            >>> sm.list_masked()
            {'API_KEY': 'sk-1***************xyz9', 'SHORT': '****'}
        """
        result: dict[str, str] = {}
        for key, value in self._cache.items():
            if value:
                # 앞 4자리만 보여주고 나머지 마스킹
                if len(value) > 8:
                    result[key] = value[:4] + "*" * (len(value) - 8) + value[-4:]
                else:
                    result[key] = "*" * len(value)
            else:
                result[key] = "(empty)"
        return result

    def export_to_shell(self) -> str:
        """셸 export 스크립트 생성

        bash/zsh에서 source로 실행 가능한 export 스크립트를 생성합니다.
        특수문자가 포함된 값은 작은따옴표로 감싸서 안전하게 이스케이핑됩니다.
        (작은따옴표 안에서는 $, ", \\ 등이 리터럴로 처리됨)

        Returns:
            bash export 형식의 문자열

        Example:
            >>> script = sm.export_to_shell()
            >>> # 생성된 스크립트를 파일로 저장 후 사용:
            >>> # source ./generated/shell_exports.sh
        """
        lines: list[str] = [
            "# Auto-generated by ai-env - DO NOT EDIT",
            f"# Source: {self.env_file}",
            "",
        ]
        for key, value in self._cache.items():
            if value and not key.startswith("#"):
                # 값에 특수문자가 있으면 작은따옴표로 감싸기
                # 작은따옴표 자체는 '\'' 패턴으로 이스케이핑
                if any(c in value for c in " $\"'\\`!"):
                    escaped = value.replace("'", "'\\''")
                    lines.append(f"export {key}='{escaped}'")
                else:
                    lines.append(f"export {key}={value}")
        return "\n".join(lines)

    def substitute(self, template: str) -> str:
        """템플릿 문자열의 ${VAR} 치환

        템플릿 문자열에서 ${변수명} 형태의 플레이스홀더를
        실제 환경변수 값으로 치환합니다.

        Args:
            template: 치환할 템플릿 문자열

        Returns:
            치환된 문자열

        Example:
            >>> sm.substitute("docker run -e TOKEN=${API_KEY}")
            'docker run -e TOKEN=sk-abc123...'
        """
        result = template
        for key, value in self._cache.items():
            result = result.replace(f"${{{key}}}", value)
        return result


def get_secrets_manager(env_file: str = ".env") -> SecretsManager:
    """SecretsManager 인스턴스 반환"""
    return SecretsManager(env_file)
