"""시크릿/환경변수 관리 모듈"""

from __future__ import annotations

import os

from dotenv import dotenv_values

from .config import get_project_root


class SecretsManager:
    """환경변수/시크릿 관리 (.env 파일에서 읽기 전용)"""

    def __init__(self, env_file: str = ".env"):
        self.env_file = get_project_root() / env_file
        self._cache: dict[str, str] = {}
        self._load()

    def _load(self) -> None:
        """환경변수 파일 로드"""
        if self.env_file.exists():
            values = dotenv_values(self.env_file)
            self._cache = {k: v for k, v in values.items() if v is not None}

    def get(self, key: str, default: str = "") -> str:
        """환경변수 값 조회"""
        return self._cache.get(key, os.environ.get(key, default))

    def list(self) -> dict[str, str]:
        """모든 환경변수 목록"""
        return self._cache.copy()

    def list_masked(self) -> dict[str, str]:
        """마스킹된 환경변수 목록 (보안)"""
        result = {}
        for key, value in self._cache.items():
            if value:
                # 앞 4자리만 보여주고 나머지 마스킹
                if len(value) > 8:
                    result[key] = value[:4] + "*" * (len(value) - 8) + value[-4:]
                else:
                    result[key] = "*" * len(value)
            else:
                result[key] = "(empty)"
        return result

    def export_to_shell(self) -> str:
        """셸 export 스크립트 생성"""
        lines = [
            "# Auto-generated by ai-env - DO NOT EDIT",
            f"# Source: {self.env_file}",
            "",
        ]
        for key, value in self._cache.items():
            if value and not key.startswith("#"):
                # 값에 특수문자가 있으면 따옴표로 감싸기
                if any(c in value for c in " $\"'\\"):
                    lines.append(f'export {key}="{value}"')
                else:
                    lines.append(f"export {key}={value}")
        return "\n".join(lines)

    def substitute(self, template: str) -> str:
        """템플릿 문자열의 ${VAR} 치환"""
        result = template
        for key, value in self._cache.items():
            result = result.replace(f"${{{key}}}", value)
        return result


def get_secrets_manager(env_file: str = ".env") -> SecretsManager:
    """SecretsManager 인스턴스 반환"""
    return SecretsManager(env_file)
